package com.example.InventoryManagementSystem.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

// HRM/payroll — one frozen snapshot row per employee per calendar month, generated by
// PayrollCalculationService (scheduled or manual, same code path either way). Every earnings/
// deduction/attendance field here is copied at generation time and never recomputed later —
// editing EmployeeSalaryConfig or backdating Attendance/Leave/Overtime after this row exists
// must never change what it already says (spec §13 — historical payroll stays stable).
@Entity
@Table(name = "salary_payments", uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "pay_period_month", "pay_period_year"}))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SalaryPayment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long salaryPaymentId;

    // Pre-deployment fix — concurrency testing found two simultaneous "mark paid" (or "cancel")
    // calls on the same PENDING row both succeeded: each read status=PENDING before either
    // committed, so the read-then-write status check in PayrollServiceImpl never saw a conflict.
    // @Version makes Hibernate include `WHERE version = ?` on every UPDATE and bump it on save;
    // whichever request loses the race gets an ObjectOptimisticLockingFailureException instead of
    // silently overwriting the winner's payment method/reference (or cancellation reason).
    @Version
    private Long version;

    @Column(unique = true)
    private String paymentNumber;

    @Column(nullable = false)
    private Long userId;

    // Reference only, not authoritative — every amount below is already snapshotted, so this
    // config row could later be edited or deactivated without affecting this payment record.
    private Long salaryConfigId;

    @Column(precision = 12, scale = 2)
    private BigDecimal basicPay;
    @Column(precision = 12, scale = 2)
    private BigDecimal hra;
    @Column(name = "other_allowances", precision = 12, scale = 2)
    private BigDecimal otherAllowances;
    @Column(precision = 12, scale = 2)
    private BigDecimal overtimeAmount;
    @Column(precision = 12, scale = 2)
    private BigDecimal deductions;
    @Column(precision = 12, scale = 2)
    private BigDecimal attendanceDeductions;
    @Column(precision = 12, scale = 2)
    private BigDecimal leaveDeductions;
    @Column(precision = 12, scale = 2)
    private BigDecimal grossPay;
    @Column(precision = 12, scale = 2)
    private BigDecimal netPay;

    // Attendance snapshot, frozen alongside the money fields — the payslip PDF (spec §27) must
    // never re-derive these from live Attendance/Leave rows after the fact.
    private Integer workingDays;
    private Integer presentDays;
    private Integer absentDays;
    private Integer paidLeaveDays;
    private Integer unpaidLeaveDays;

    @Column(nullable = false)
    private Integer payPeriodMonth;
    @Column(nullable = false)
    private Integer payPeriodYear;

    // PENDING -> PAID | PENDING -> CANCELLED. PAID and CANCELLED are terminal in V1 — no reverse
    // transition (spec §15/§16). Never physically deleted once created.
    @Builder.Default
    private String status = "PENDING";

    private OffsetDateTime generatedAt;
    private Long generatedBy;
    // SCHEDULED | MANUAL — which trigger created this row.
    private String generationSource;

    private OffsetDateTime paidAt;
    private Long paidByUserId;
    // CASH | BANK_TRANSFER | UPI | CHEQUE | OTHER
    private String paymentMethod;
    private String paymentReference;

    private OffsetDateTime cancelledAt;
    private Long cancelledByUserId;
    @Column(columnDefinition = "TEXT")
    private String cancellationReason;

    @Column(columnDefinition = "TEXT")
    private String notes;
}
